"""
Flask web dashboard for Theme 3: Smart Government — Malaysian Cost of Living.
Serves 4 tabs: Overview, Time Series Forecast, Clustering, Fuel Analysis.
Plots are pre-generated by the pipeline and served as static images.
Dynamic sections use lightweight JSON API endpoints.
"""

import os
import sys
import json
import subprocess
import threading
import queue
from functools import lru_cache
import pandas as pd
from flask import Flask, render_template, jsonify, request, send_from_directory, Response, stream_with_context

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(BASE_DIR, "..")
sys.path.insert(0, ROOT_DIR)

FIGURES_DIR = os.path.join(ROOT_DIR, "outputs", "figures")
MODELS_DIR = os.path.join(ROOT_DIR, "outputs", "models")
PROCESSED_DIR = os.path.join(ROOT_DIR, "data", "processed")

app = Flask(__name__, template_folder="templates")


# ─── Helpers: load and cache results ─────────────────────────────────────────

@lru_cache(maxsize=None)
def _load_arima():
    with open(os.path.join(MODELS_DIR, "arima_results.json")) as f:
        return json.load(f)


@lru_cache(maxsize=None)
def _load_clustering():
    with open(os.path.join(MODELS_DIR, "clustering_results.json")) as f:
        return json.load(f)


@lru_cache(maxsize=None)
def _load_fuel_correlation():
    path = os.path.join(MODELS_DIR, "fuel_correlation.json")
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


@lru_cache(maxsize=None)
def _load_df(name):
    return pd.read_csv(os.path.join(PROCESSED_DIR, name))


def _pipeline_ready():
    required = [
        os.path.join(MODELS_DIR, "arima_results.json"),
        os.path.join(MODELS_DIR, "clustering_results.json"),
        os.path.join(PROCESSED_DIR, "overall_inflation.csv"),
        os.path.join(PROCESSED_DIR, "states_kmeans_clustered.csv"),
        os.path.join(PROCESSED_DIR, "cpi_state_clean.csv"),
    ]
    return all(os.path.exists(p) for p in required)


def _not_ready():
    return jsonify({"error": "Pipeline has not been run yet. POST /api/run to start it."}), 503


# ─── Routes ──────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/status")
def api_status():
    return jsonify({"ready": _pipeline_ready()})


@app.route("/api/overview")
def api_overview():
    """National overall inflation trend — last 5 years, monthly."""
    if not _pipeline_ready():
        return _not_ready()
    df = _load_df("overall_inflation.csv")
    df["date"] = pd.to_datetime(df["date"])
    cutoff = df["date"].max() - pd.DateOffset(years=5)
    recent = df[df["date"] >= cutoff][["date", "inflation_yoy", "inflation_mom"]].copy()
    recent["date"] = recent["date"].dt.strftime("%Y-%m-%d")
    return jsonify(recent.to_dict(orient="records"))


@app.route("/api/overview/divisions")
def api_overview_divisions():
    """All divisions inflation — last 3 years for the division trends chart."""
    if not _pipeline_ready():
        return _not_ready()
    df = _load_df("cpi_inflation_clean.csv")
    df["date"] = pd.to_datetime(df["date"])
    cutoff = df["date"].max() - pd.DateOffset(years=3)
    recent = df[df["date"] >= cutoff].dropna(subset=["inflation_yoy"])
    recent = recent[["date", "division", "division_label", "inflation_yoy"]].copy()
    recent["date"] = recent["date"].dt.strftime("%Y-%m-%d")
    return jsonify(recent.to_dict(orient="records"))


@app.route("/api/ts/forecast")
def api_ts_forecast():
    """Full ARIMA forecast result — train, test, and future horizon."""
    if not _pipeline_ready():
        return _not_ready()
    result = _load_arima()
    return jsonify({
        "train":      result["train"],
        "test":       result["test"],
        "forecast":   result["forecast"],
        "metrics":    result["metrics"],
        "stationarity": result["stationarity"],
        "arima_order": result["arima_order"],
        "aic":         result.get("aic"),
        "bic":         result.get("bic"),
        "horizon":     result.get("horizon"),
        "series_length": result.get("series_length"),
        "test_months": result.get("test_months"),
    })


@app.route("/api/ts/metrics")
def api_ts_metrics():
    """ARIMA evaluation metrics summary table."""
    if not _pipeline_ready():
        return _not_ready()
    path = os.path.join(MODELS_DIR, "ts_metrics_summary.csv")
    df = pd.read_csv(path)
    return jsonify(df.to_dict(orient="records"))


@app.route("/api/ts/live")
def api_ts_live():
    """SSE endpoint — runs ARIMA live on national CPI inflation and streams progress."""
    try:
        horizon = min(max(int(request.args.get("horizon", 24)), 1), 48)
    except ValueError:
        horizon = 24

    def generate():
        from src.time_series import run_live
        inflation_path = os.path.join(PROCESSED_DIR, "overall_inflation.csv")
        if not os.path.exists(inflation_path):
            yield f'data: {json.dumps({"type": "error", "message": "Run the pipeline first."})}\n\n'
            return
        inflation_df = _load_df("overall_inflation.csv")
        inflation_df = inflation_df.copy()
        inflation_df["date"] = pd.to_datetime(inflation_df["date"])
        # Pass pre-computed results so run_live can skip all model fitting
        precomputed_order = None
        precomputed_data = None
        try:
            arima_data = _load_arima()
            order_list = arima_data.get("arima_order") or arima_data.get("order")
            if order_list and len(order_list) == 3:
                precomputed_order = tuple(int(x) for x in order_list)
                precomputed_data = arima_data
        except Exception:
            pass
        for event in run_live(inflation_df, horizon=horizon,
                              order=precomputed_order, precomputed=precomputed_data):
            yield f"data: {json.dumps(event)}\n\n"

    return Response(
        stream_with_context(generate()),
        mimetype="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.route("/api/cluster/states")
def api_cluster_states():
    """Cluster assignment per state. ?method=kmeans (default) or hierarchical."""
    if not _pipeline_ready():
        return _not_ready()
    method = request.args.get("method", "kmeans").lower()
    fname = ("states_hierarchical_clustered.csv" if method == "hierarchical"
             else "states_kmeans_clustered.csv")
    df = _load_df(fname)
    return jsonify(df.to_dict(orient="records"))


@app.route("/api/cluster/metrics")
def api_cluster_metrics():
    """Comparison of K-Means vs Hierarchical clustering evaluation scores."""
    if not _pipeline_ready():
        return _not_ready()
    path = os.path.join(MODELS_DIR, "cluster_metrics_summary.csv")
    df = pd.read_csv(path)
    return jsonify(df.to_dict(orient="records"))


@app.route("/api/cluster/elbow")
def api_cluster_elbow():
    """Elbow / silhouette / Davies-Bouldin curves used to choose k."""
    if not _pipeline_ready():
        return _not_ready()
    res = _load_clustering()
    return jsonify({
        "elbow_metrics": res.get("elbow_metrics", {}),
        "best_k": res.get("best_k"),
        "pca_variance": res.get("pca_variance", []),
    })


@app.route("/api/cluster/dendrogram")
def api_cluster_dendrogram():
    """Drawable coordinates for an interactive hierarchical dendrogram."""
    if not _pipeline_ready():
        return _not_ready()
    dn = _load_clustering().get("dendrogram")
    if not dn:
        return jsonify({"error": "Dendrogram data not available."}), 404
    return jsonify(dn)


@app.route("/api/fuel/exog")
def api_fuel_exog():
    """ARIMAX (fuel as exogenous regressor) vs univariate ARIMA experiment."""
    if not _pipeline_ready():
        return _not_ready()
    exp = _load_arima().get("fuel_exog_experiment")
    if not exp:
        return jsonify({"available": False, "reason": "Not computed."}), 404
    return jsonify(exp)


@app.route("/api/fuel/prices")
def api_fuel_prices():
    """Monthly resampled fuel prices (RON95, RON97, Diesel)."""
    if not _pipeline_ready():
        return _not_ready()
    df = _load_df("fuelprice_clean.csv").copy()
    df["date"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")
    df = df.dropna(subset=["ron95", "ron97", "diesel"])
    return jsonify(df.to_dict(orient="records"))


@app.route("/api/fuel/correlation")
def api_fuel_correlation():
    """Pearson correlation between fuel prices and CPI inflation."""
    if not _pipeline_ready():
        return _not_ready()
    corr = _load_fuel_correlation()
    if corr is None:
        return jsonify({"error": "Fuel correlation data not available"}), 404
    return jsonify({
        "correlations": corr["correlations"],
        "n_overlap_months": corr["n_overlap_months"],
        "overlap_start": corr["overlap_start"],
        "overlap_end": corr["overlap_end"],
    })


@app.route("/api/cpi/states")
def api_cpi_states():
    """List of states available in the CPI state dataset."""
    if not _pipeline_ready():
        return _not_ready()
    df = _load_df("cpi_state_clean.csv")
    return jsonify(sorted(df["state"].unique().tolist()))


@app.route("/api/cpi/state")
def api_cpi_state():
    """Monthly overall CPI index for a single state."""
    if not _pipeline_ready():
        return _not_ready()
    state = request.args.get("state", "Johor")
    df = _load_df("cpi_state_clean.csv")
    df["date"] = pd.to_datetime(df["date"])
    filtered = df[(df["state"] == state) & (df["division"] == "overall")][
        ["date", "index"]
    ].copy()
    filtered["date"] = filtered["date"].dt.strftime("%Y-%m-%d")
    return jsonify(filtered.to_dict(orient="records"))


@app.route("/figure/<path:filename>")
def serve_figure(filename):
    return send_from_directory(FIGURES_DIR, filename)


# ─── Pipeline trigger with Server-Sent Events streaming ──────────────────────

_pipeline_lock = threading.Lock()
_pipeline_running = False
_pipeline_proc = None   # handle to the running subprocess, for cancellation


@app.route("/api/run/cancel", methods=["POST"])
def api_cancel_pipeline():
    """Terminate the currently running pipeline subprocess, if any."""
    global _pipeline_proc
    proc = _pipeline_proc
    if proc is not None and proc.poll() is None:
        proc.terminate()
        return jsonify({"cancelled": True})
    return jsonify({"cancelled": False, "reason": "No pipeline running."})


@app.route("/api/run", methods=["POST"])
def api_run_pipeline():
    """
    Spawn the pipeline as a subprocess and stream stdout line-by-line
    back to the browser via Server-Sent Events (SSE).
    Only one pipeline run is allowed at a time.
    """
    global _pipeline_running
    if not _pipeline_lock.acquire(blocking=False):
        return jsonify({"error": "Pipeline is already running."}), 409

    _pipeline_running = True
    log_queue = queue.Queue()
    pipeline_script = os.path.join(ROOT_DIR, "run_pipeline.py")

    def _run():
        global _pipeline_proc
        try:
            proc = subprocess.Popen(
                [sys.executable, "-u", pipeline_script, "--no-dashboard"],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                cwd=ROOT_DIR,
            )
            _pipeline_proc = proc
            for line in proc.stdout:
                log_queue.put(line.rstrip())
            proc.wait()
            if proc.returncode is not None and proc.returncode < 0:
                log_queue.put("⚠ Pipeline cancelled by user.")
            log_queue.put(f"__EXIT__{proc.returncode}")
        except Exception as e:
            log_queue.put("__EXIT__1")
            log_queue.put(f"ERROR: {e}")
        finally:
            _pipeline_proc = None
            _load_arima.cache_clear()
            _load_clustering.cache_clear()
            _load_fuel_correlation.cache_clear()
            _load_df.cache_clear()
            global _pipeline_running
            _pipeline_running = False
            _pipeline_lock.release()

    thread = threading.Thread(target=_run, daemon=True)
    thread.start()

    # A single pipeline step (e.g. the ARIMA BIC grid search) can run for a
    # while without printing. Rather than give up on the first quiet stretch,
    # poll briefly and emit an SSE heartbeat comment to keep the connection
    # alive; only abort after a genuinely long total silence as a safety net.
    HEARTBEAT_SECS = 15
    MAX_SILENCE_SECS = 300  # 5 min with zero output → assume something hung

    def _stream():
        yield "retry: 1000\n\n"
        silence = 0
        while True:
            try:
                line = log_queue.get(timeout=HEARTBEAT_SECS)
            except queue.Empty:
                silence += HEARTBEAT_SECS
                if silence >= MAX_SILENCE_SECS:
                    yield "data: [timeout — pipeline appears to have stalled]\n\n"
                    break
                yield ": keepalive\n\n"   # SSE comment, ignored by the browser
                continue
            silence = 0
            if line.startswith("__EXIT__"):
                code = line.split("__")[2]
                yield f"event: done\ndata: {code}\n\n"
                break
            yield f"data: {line}\n\n"

    return Response(
        stream_with_context(_stream()),
        mimetype="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


if __name__ == "__main__":
    # debug=False: never expose the Werkzeug interactive debugger on 0.0.0.0.
    app.run(host="0.0.0.0", debug=False, port=5050)
