"""
Flask web dashboard for Theme 3: Smart Government.
Serves 4 tabs: Overview, Time Series Forecast, Clustering, Poverty Analysis.
Plots are pre-generated by the pipeline and served as static images.
Dynamic sections (state selector, table) use lightweight JSON API endpoints.
"""

import os
import sys
import json
from functools import lru_cache
import pandas as pd
from flask import Flask, render_template, jsonify, request, send_from_directory

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(BASE_DIR, "..")
sys.path.insert(0, ROOT_DIR)

FIGURES_DIR = os.path.join(ROOT_DIR, "outputs", "figures")
MODELS_DIR = os.path.join(ROOT_DIR, "outputs", "models")
PROCESSED_DIR = os.path.join(ROOT_DIR, "data", "processed")

app = Flask(__name__, template_folder="templates")


# ─── Helpers: load and cache results (disk read once per process) ─────────────

@lru_cache(maxsize=None)
def _load_arima():
    with open(os.path.join(MODELS_DIR, "arima_results.json")) as f:
        return json.load(f)


@lru_cache(maxsize=None)
def _load_clustering():
    with open(os.path.join(MODELS_DIR, "clustering_results.json")) as f:
        return json.load(f)


@lru_cache(maxsize=None)
def _load_df(name):
    return pd.read_csv(os.path.join(PROCESSED_DIR, name))


# ─── Routes ──────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/overview")
def api_overview():
    df = _load_df("hies_state_clean.csv")
    return jsonify(df.to_dict(orient="records"))


@app.route("/api/ts/states")
def api_ts_states():
    results = _load_arima()
    return jsonify(sorted([s for s, r in results.items() if "error" not in r]))


@app.route("/api/ts/forecast")
def api_ts_forecast():
    state = request.args.get("state", "Johor")
    results = _load_arima()
    if state not in results:
        return jsonify({"error": "State not found"}), 404
    r = results[state]
    if "error" in r:
        return jsonify(r), 400
    return jsonify({
        "train": {"years": r["train_years"], "gini": r["train_gini"]},
        "test": {
            "years": r["test_years"],
            "actual": r["test_gini"],
            "predicted": r["test_pred"],
        },
        "forecast": {"years": r["forecast_years"], "gini": r["forecast_gini"]},
        "metrics": r["metrics"],
        "stationarity": r["stationarity"],
    })


@app.route("/api/ts/metrics")
def api_ts_metrics():
    path = os.path.join(MODELS_DIR, "ts_metrics_summary.csv")
    df = pd.read_csv(path)
    return jsonify(df.to_dict(orient="records"))


@app.route("/api/cluster/districts")
def api_cluster_districts():
    df = _load_df("districts_kmeans_clustered.csv")
    state = request.args.get("state", None)
    if state:
        df = df[df["state"] == state]
    return jsonify(df.to_dict(orient="records"))


@app.route("/api/cluster/metrics")
def api_cluster_metrics():
    path = os.path.join(MODELS_DIR, "cluster_metrics_summary.csv")
    df = pd.read_csv(path)
    return jsonify(df.to_dict(orient="records"))


@app.route("/api/poverty/districts")
def api_poverty_districts():
    df = _load_df("poverty_district_wide.csv")
    state = request.args.get("state", None)
    if state:
        df = df[df["state"] == state]
    return jsonify(df.to_dict(orient="records"))


@app.route("/api/poverty/states")
def api_poverty_states():
    df = _load_df("hies_district_clean.csv")
    return jsonify(sorted(df["state"].unique().tolist()))


@app.route("/figure/<path:filename>")
def serve_figure(filename):
    return send_from_directory(FIGURES_DIR, filename)


if __name__ == "__main__":
    app.run(debug=True, port=5050)
